/* Replace with your SQL commands */
DROP TABLE IF EXISTS contient;

DROP TABLE IF EXISTS comporte;

DROP TABLE IF EXISTS RAPPORT_VETERINAIRE;

DROP TABLE IF EXISTS ANIMAL;

DROP TABLE IF EXISTS HABITAT;

DROP TABLE IF EXISTS IMAGE;

DROP TABLE IF EXISTS SERVICE;

DROP TABLE IF EXISTS AVIS;

DROP TABLE IF EXISTS RACE;

DROP TABLE IF EXISTS UTILISATEUR;

DROP TABLE IF EXISTS ROLE;